// let height=prompt("Enter the height of triangle")
// let base=prompt("Enter base of triangle")
// let area =(0.5*height*base)
// console.log("AREA OF TRIANGLE IS " + area)

// let cylheight=prompt("Enter the height of cylinder")
// let cylrad=prompt("Enter the radius of triangle")
// //let pi=3.14;
//  let vol=(Math.PI*cylrad*cylrad*cylheight)
//  console.log("VOLUME OF CYLINDER IS "+ vol )
//  let cylarea=(2*Math.PI *cylrad *cylrad+cylheight)
//  console.log("AREA OF CYLINDER IS "+ cylarea)
//  console.log("After round of "+ Math.floor(cylarea))